### ISSUE TITLE
Installation in Debian 8.2 Systemd-nspawn container fails: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by udono** [systemd/python-systemd#17]
Hi,
following the installation instructions from https://github.com/systemd/python-systemd/blob/master/README.md I would like to use python-systemd (Python2.7) in a systemd-nspawn container with Debian 8.2 OS.

I tried to install the Debian distribution, but it is not found:

    sudo apt-get install python-systemd 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package python-systemd

Installing the dev dependencies works:

    apt-get install libsystemd-{journal,daemon,login,id128}-dev gcc python-dev
    […]
    gcc is already the newest version.
    python-dev is already the newest version.
    libsystemd-daemon-dev is already the newest version.
    libsystemd-id128-dev is already the newest version.
    libsystemd-journal-dev is already the newest version.
    libsystemd-login-dev is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

But when I try one of the following installation methods, I get an error.
Using pip:

    pip install git+https://github.com/systemd/python-systemd.git#egg=systemd
	Downloading/unpacking systemd from git+https://github.com/systemd/python-systemd.git
	  Cloning https://github.com/systemd/python-systemd.git to /tmp/pip-build-62myFr/systemd
	  Running setup.py (path:/tmp/pip-build-62myFr/systemd/setup.py) egg_info for package systemd
	    Traceback (most recent call last):
	      File "<string>", line 17, in <module>
	      File "/tmp/pip-build-62myFr/systemd/setup.py", line 64, in <module>
		**lib('libsystemd', 'libsystemd-journal', **defines))
	      File "/tmp/pip-build-62myFr/systemd/setup.py", line 50, in lib
		status, result = pkgconfig(name, **kw)
	      File "/tmp/pip-build-62myFr/systemd/setup.py", line 32, in pkgconfig
		status, result = call('pkg-config', '--libs', '--cflags', package)
	      File "/tmp/pip-build-62myFr/systemd/setup.py", line 24, in call
		universal_newlines=True)
	      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
		errread, errwrite)
	      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
		raise child_exception
	    OSError: [Errno 2] No such file or directory
	    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):
	  File "<string>", line 17, in <module>
	  File "/tmp/pip-build-62myFr/systemd/setup.py", line 64, in <module>
	    **lib('libsystemd', 'libsystemd-journal', **defines))
	  File "/tmp/pip-build-62myFr/systemd/setup.py", line 50, in lib
	    status, result = pkgconfig(name, **kw)
	  File "/tmp/pip-build-62myFr/systemd/setup.py", line 32, in pkgconfig
	    status, result = call('pkg-config', '--libs', '--cflags', package)
	  File "/tmp/pip-build-62myFr/systemd/setup.py", line 24, in call
	    universal_newlines=True)
	  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
	    errread, errwrite)
	  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
	    raise child_exception
	OSError: [Errno 2] No such file or directory
	----------------------------------------
	Cleaning up...
	Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-62myFr/systemd
	Storing debug log for failure in /root/.pip/pip.log

the same using setup.py install directly:

    python-systemd$ python setup.py install
    Traceback (most recent call last):
      File "setup.py", line 64, in <module>
        **lib('libsystemd', 'libsystemd-journal', **defines))
      File "setup.py", line 50, in lib
        status, result = pkgconfig(name, **kw)
      File "setup.py", line 32, in pkgconfig
        status, result = call('pkg-config', '--libs', '--cflags', package)
      File "setup.py", line 24, in call
        universal_newlines=True)
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

TIA, regards Udo

**Comment by baites** [comment]
I had the same problem in ubuntu 15.04 and I fixed it  by installing pkg-config. So this is what I am doing

apt-get install gcc libsystemd-{journal,daemon,login,id128}-dev python-dev pkg-config
pip install git+https://github.com/systemd/python-systemd.git#egg=systemd

Let me known if this works for you.

**Comment by udono** [comment]
it works for me, too. Thanks a lot!

**Comment by keszybz** [comment]
Yeah, pkg-config is required.
